---
- hosts: webserver
  become: true
  tasks:
    - name: Installing Nginx HTTP & Reverse Proxy server
      apt: name=nginx state=installed update_cache=yes

    - name: start tthe nginx webserver
      service: name=nginx state=started enabled=yes

    - name: Copy the webpages 
      copy: src=./files/index.html dest=/var/www/html/ mode=0644

    - name: restart the nginx
      service: name=nginx state=restarted 

       
